name: terminal-parrot # check to see if it's available
version: '1.3+git' # check versioning
summary: Parrot for your terminal # 79 char long summary
description: |
  You didn't know there was a party in your terminal, but there is! 
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

apps:
  terminal-parrot:
    command: terminal-parrot
    plugs:
      - home
     
parts: 
  my-part:
    source: .
    source-type: git
    plugin: go
    go-importpath: github.com/kz6fittycent/terminal-parrot
